"""Frozen, human-auditable evaluation for claim extraction quality.

The production harness records what it did.  This module evaluates whether
the extracted semantic claims were good.  Keeping those responsibilities
separate prevents a successful model call, a located anchor, or a populated
record from being mistaken for entailment, coverage, or decontextualization.

The metric axes follow Claimify's evaluation framing.  Semantic judgements are
inputs to this module, not generated by it; pending human review never counts
as a zero or as a pass.
"""

from __future__ import annotations

from enum import Enum
from statistics import fmean

from pydantic import AliasChoices, BaseModel, ConfigDict, Field, model_validator


class ClaimReviewStatus(str, Enum):
    """Whether a human-approved semantic judgement is available."""

    PENDING_REVIEW = "pending_review"
    REVIEWED = "reviewed"


class ClaimEntailmentLabel(str, Enum):
    """Gold relation from the report surface/context to one claim."""

    ENTAILED = "entailed"
    NOT_ENTAILED = "not_entailed"
    AMBIGUOUS = "ambiguous"


class ClaimAmbiguityLabel(str, Enum):
    """Whether the source meaning is usable without guessing."""

    UNAMBIGUOUS = "unambiguous"
    RESOLVED_FROM_CONTEXT = "resolved_from_context"
    CANNOT_DISAMBIGUATE = "cannot_disambiguate"


class ClaimGoldDisposition(str, Enum):
    """Human judgement about whether the frozen text has factual work.

    This is deliberately not inferred from whether a system happened to emit
    a claim.  In particular, ``no_verifiable_claims`` gives reviewers an
    honest representation for normative or purely rhetorical text instead of
    forcing them to invent a preferred decomposition.
    """

    VERIFICATION_UNITS = "verification_units"
    NO_VERIFIABLE_CLAIMS = "no_verifiable_claims"
    CANNOT_DISAMBIGUATE = "cannot_disambiguate"


class FrozenSurfaceSpan(BaseModel):
    """One exact span relative to the frozen Markdown block snapshot."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    text: str = Field(min_length=1)
    start_char: int = Field(ge=0)
    end_char: int = Field(ge=0)

    @model_validator(mode="after")
    def _bounds_match_text(self) -> FrozenSurfaceSpan:
        if self.end_char <= self.start_char:
            raise ValueError("surface end_char must exceed start_char")
        if self.end_char - self.start_char != len(self.text):
            raise ValueError("surface bounds must match text length")
        return self


class FrozenClaimExtractionCase(BaseModel):
    """Immutable real input; semantic gold lives in a separate annotation."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    case_id: str = Field(min_length=1)
    source_run_id: str = Field(min_length=1)
    audit_view: str = Field(min_length=1)
    original_claim_id: str = Field(min_length=1)
    block_id: str = Field(min_length=1)
    report_text_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    block_text: str = Field(min_length=1)
    observed_selected_text: str = Field(min_length=1)
    observed_claim_text: str = Field(min_length=1)
    observed_failure: str = Field(min_length=1)
    addressable_spans: tuple[FrozenSurfaceSpan, ...]

    @model_validator(mode="after")
    def _addressable_spans_are_exact_and_ordered(
        self,
    ) -> FrozenClaimExtractionCase:
        previous_end = -1
        for span in self.addressable_spans:
            if self.block_text[span.start_char : span.end_char] != span.text:
                raise ValueError("addressable span must round-trip to block text")
            if span.start_char < previous_end:
                raise ValueError("addressable spans must be ordered and nonoverlapping")
            previous_end = span.end_char
        return self


class ClaimExtractionGold(BaseModel):
    """Human-approved source interpretation for one frozen case."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    case_id: str = Field(min_length=1)
    review_status: ClaimReviewStatus
    gold_disposition: ClaimGoldDisposition | None = None
    acceptable_surface_spans: tuple[FrozenSurfaceSpan, ...] = ()
    ambiguity: ClaimAmbiguityLabel | None = None
    truth_conditional_elements: tuple[str, ...] = Field(
        default=(),
        validation_alias=AliasChoices(
            "truth_conditional_elements",
            "verifiable_elements",
        ),
    )
    necessary_context: tuple[str, ...] = ()
    preferred_verification_units: tuple[str, ...] = Field(
        default=(),
        validation_alias=AliasChoices(
            "preferred_verification_units",
            "preferred_atomic_claims",
        ),
    )
    reviewer: str | None = None
    rationale: str | None = None

    @model_validator(mode="after")
    def _reviewed_gold_is_substantive(self) -> ClaimExtractionGold:
        if self.review_status is ClaimReviewStatus.PENDING_REVIEW:
            if any(
                (
                    self.gold_disposition,
                    self.acceptable_surface_spans,
                    self.truth_conditional_elements,
                    self.necessary_context,
                    self.preferred_verification_units,
                )
            ) or any((self.ambiguity, self.reviewer, self.rationale)):
                raise ValueError("pending gold cannot contain guessed annotations")
            return self
        if self.gold_disposition is None or self.reviewer is None:
            raise ValueError(
                "reviewed gold requires gold_disposition and reviewer"
            )
        if not self.rationale:
            raise ValueError("reviewed gold requires a rationale")
        if self.gold_disposition is ClaimGoldDisposition.VERIFICATION_UNITS:
            if self.ambiguity is None:
                raise ValueError(
                    "verification-unit gold requires an ambiguity label"
                )
            if self.ambiguity is ClaimAmbiguityLabel.CANNOT_DISAMBIGUATE:
                raise ValueError(
                    "usable verification units cannot be cannot_disambiguate"
                )
            if not self.acceptable_surface_spans:
                raise ValueError(
                    "verification-unit gold requires a report surface span"
                )
            if not self.truth_conditional_elements:
                raise ValueError(
                    "verification-unit gold requires truth-conditional elements"
                )
            if not self.preferred_verification_units:
                raise ValueError(
                    "verification-unit gold requires preferred units"
                )
            return self

        if any(
            (
                self.acceptable_surface_spans,
                self.truth_conditional_elements,
                self.preferred_verification_units,
            )
        ):
            raise ValueError(
                "gold without verification units cannot contain guessed units"
            )
        if (
            self.gold_disposition
            is ClaimGoldDisposition.CANNOT_DISAMBIGUATE
            and self.ambiguity is not ClaimAmbiguityLabel.CANNOT_DISAMBIGUATE
        ):
            raise ValueError(
                "cannot_disambiguate disposition requires matching ambiguity"
            )
        if (
            self.gold_disposition
            is ClaimGoldDisposition.NO_VERIFIABLE_CLAIMS
            and self.ambiguity is ClaimAmbiguityLabel.CANNOT_DISAMBIGUATE
        ):
            raise ValueError(
                "no_verifiable_claims must not masquerade as ambiguity"
            )
        return self


class ExtractedClaimJudgement(BaseModel):
    """Human judgement of one system-produced semantic claim."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    claim_text: str = Field(min_length=1)
    entailment: ClaimEntailmentLabel
    verification_unit_appropriate: bool = Field(
        validation_alias=AliasChoices(
            "verification_unit_appropriate",
            "atomic",
        )
    )
    preserves_truth_conditions: bool
    decontextualized: bool
    covered_element_ids: tuple[int, ...] = ()
    extraneous_element_count: int = Field(default=0, ge=0)
    rationale: str = Field(min_length=1)

    @model_validator(mode="after")
    def _element_ids_are_unique_nonnegative(self) -> ExtractedClaimJudgement:
        if any(index < 0 for index in self.covered_element_ids):
            raise ValueError("covered element IDs must be nonnegative")
        if len(set(self.covered_element_ids)) != len(self.covered_element_ids):
            raise ValueError("covered element IDs must be unique")
        return self


class ClaimExtractionSystemJudgement(BaseModel):
    """Human review of one system output on one frozen input case."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    case_id: str = Field(min_length=1)
    system_id: str = Field(min_length=1)
    review_status: ClaimReviewStatus
    selected_surface_spans: tuple[FrozenSurfaceSpan, ...] = ()
    claims: tuple[ExtractedClaimJudgement, ...] = ()
    reviewer: str | None = None

    @model_validator(mode="after")
    def _pending_output_has_no_semantic_scores(
        self,
    ) -> ClaimExtractionSystemJudgement:
        if self.review_status is ClaimReviewStatus.PENDING_REVIEW:
            if self.selected_surface_spans or self.claims or self.reviewer:
                raise ValueError("pending system judgement cannot contain labels")
        elif self.reviewer is None:
            raise ValueError("reviewed system judgement requires reviewer")
        return self


class ClaimExtractionMetrics(BaseModel):
    """Separate axes; intentionally no composite success score."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    system_id: str
    total_cases: int = Field(ge=0)
    reviewed_cases: int = Field(ge=0)
    reviewed_case_ids: tuple[str, ...]
    pending_case_ids: tuple[str, ...]
    surface_binding_accuracy: float | None = Field(default=None, ge=0, le=1)
    entailment_rate: float | None = Field(default=None, ge=0, le=1)
    verification_unit_appropriateness_rate: float | None = Field(
        default=None,
        ge=0,
        le=1,
    )
    truth_condition_preservation_rate: float | None = Field(
        default=None,
        ge=0,
        le=1,
    )
    decontextualization_rate: float | None = Field(default=None, ge=0, le=1)
    element_precision: float | None = Field(default=None, ge=0, le=1)
    element_recall: float | None = Field(default=None, ge=0, le=1)
    element_f1: float | None = Field(default=None, ge=0, le=1)

    @model_validator(mode="after")
    def _case_partition_is_explicit(self) -> ClaimExtractionMetrics:
        if self.reviewed_cases != len(self.reviewed_case_ids):
            raise ValueError("reviewed_cases must match reviewed_case_ids")
        if self.total_cases != len(self.reviewed_case_ids) + len(
            self.pending_case_ids
        ):
            raise ValueError("reviewed and pending cases must partition total_cases")
        all_ids = self.reviewed_case_ids + self.pending_case_ids
        if len(set(all_ids)) != len(all_ids):
            raise ValueError("reviewed and pending case IDs must be unique")
        return self


class PairedClaimExtractionComparison(BaseModel):
    """Metric deltas over the exact same frozen, reviewed cases."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    baseline: ClaimExtractionMetrics
    candidate: ClaimExtractionMetrics
    paired_case_ids: tuple[str, ...]
    metric_deltas: dict[str, float]


def evaluate_claim_extraction(
    cases: tuple[FrozenClaimExtractionCase, ...],
    gold: tuple[ClaimExtractionGold, ...],
    judgements: tuple[ClaimExtractionSystemJudgement, ...],
) -> ClaimExtractionMetrics:
    """Evaluate only human-reviewed intersections; pending stays explicit."""

    case_by_id = {case.case_id: case for case in cases}
    if len(case_by_id) != len(cases):
        raise ValueError("frozen claim-extraction case IDs must be unique")
    gold_by_id = {item.case_id: item for item in gold}
    judgement_by_id = {item.case_id: item for item in judgements}
    if len(gold_by_id) != len(gold) or len(judgement_by_id) != len(judgements):
        raise ValueError("gold and judgement case IDs must be unique")
    unknown = (set(gold_by_id) | set(judgement_by_id)) - set(case_by_id)
    if unknown:
        raise ValueError(f"unknown frozen case IDs: {sorted(unknown)}")
    system_ids = {item.system_id for item in judgements}
    if len(system_ids) != 1:
        raise ValueError("one evaluation call requires exactly one system_id")
    system_id = next(iter(system_ids))

    reviewed_ids = tuple(
        case.case_id
        for case in cases
        if (
            (gold_item := gold_by_id.get(case.case_id)) is not None
            and gold_item.review_status is ClaimReviewStatus.REVIEWED
            and (judged := judgement_by_id.get(case.case_id)) is not None
            and judged.review_status is ClaimReviewStatus.REVIEWED
        )
    )
    pending_ids = tuple(
        case.case_id for case in cases if case.case_id not in reviewed_ids
    )
    if not reviewed_ids:
        return ClaimExtractionMetrics(
            system_id=system_id,
            total_cases=len(cases),
            reviewed_cases=0,
            reviewed_case_ids=(),
            pending_case_ids=pending_ids,
        )

    surface_scores: list[float] = []
    entailment_scores: list[float] = []
    verification_unit_scores: list[float] = []
    preservation_scores: list[float] = []
    decontext_scores: list[float] = []
    precision_scores: list[float] = []
    recall_scores: list[float] = []
    for case_id in reviewed_ids:
        case = case_by_id[case_id]
        gold_item = gold_by_id[case_id]
        judged = judgement_by_id[case_id]
        assert gold_item.review_status is ClaimReviewStatus.REVIEWED
        assert judged.review_status is ClaimReviewStatus.REVIEWED

        mechanically_exact = all(
            case.block_text[span.start_char : span.end_char] == span.text
            for span in judged.selected_surface_spans
        )
        selected_keys = {
            (span.start_char, span.end_char, span.text)
            for span in judged.selected_surface_spans
        }
        gold_keys = {
            (span.start_char, span.end_char, span.text)
            for span in gold_item.acceptable_surface_spans
        }
        surface_scores.append(
            float(mechanically_exact and selected_keys == gold_keys)
        )
        for claim in judged.claims:
            entailment_scores.append(
                float(claim.entailment is ClaimEntailmentLabel.ENTAILED)
            )
            verification_unit_scores.append(
                float(claim.verification_unit_appropriate)
            )
            preservation_scores.append(float(claim.preserves_truth_conditions))
            decontext_scores.append(float(claim.decontextualized))

        element_total = len(gold_item.truth_conditional_elements)
        covered = {
            index
            for claim in judged.claims
            for index in claim.covered_element_ids
        }
        if any(index >= element_total for index in covered):
            raise ValueError(f"covered element ID out of range for {case_id}")
        extraneous = sum(
            claim.extraneous_element_count for claim in judged.claims
        )
        precision_scores.append(
            len(covered) / (len(covered) + extraneous)
            if covered or extraneous
            else 1.0
        )
        recall_scores.append(
            len(covered) / element_total if element_total else 1.0
        )

    precision = fmean(precision_scores)
    recall = fmean(recall_scores)
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    return ClaimExtractionMetrics(
        system_id=system_id,
        total_cases=len(cases),
        reviewed_cases=len(reviewed_ids),
        reviewed_case_ids=reviewed_ids,
        pending_case_ids=pending_ids,
        surface_binding_accuracy=fmean(surface_scores),
        entailment_rate=(fmean(entailment_scores) if entailment_scores else None),
        verification_unit_appropriateness_rate=(
            fmean(verification_unit_scores)
            if verification_unit_scores
            else None
        ),
        truth_condition_preservation_rate=(
            fmean(preservation_scores) if preservation_scores else None
        ),
        decontextualization_rate=(
            fmean(decontext_scores) if decontext_scores else None
        ),
        element_precision=precision,
        element_recall=recall,
        element_f1=f1,
    )


def compare_claim_extraction(
    baseline: ClaimExtractionMetrics,
    candidate: ClaimExtractionMetrics,
) -> PairedClaimExtractionComparison:
    """Compare only identical reviewed case sets; moving sets are rejected."""

    if baseline.reviewed_case_ids != candidate.reviewed_case_ids:
        raise ValueError("paired comparison requires identical ordered case IDs")
    metric_names = (
        "surface_binding_accuracy",
        "entailment_rate",
        "verification_unit_appropriateness_rate",
        "truth_condition_preservation_rate",
        "decontextualization_rate",
        "element_precision",
        "element_recall",
        "element_f1",
    )
    deltas: dict[str, float] = {}
    for name in metric_names:
        before = getattr(baseline, name)
        after = getattr(candidate, name)
        if before is not None and after is not None:
            deltas[name] = after - before
    return PairedClaimExtractionComparison(
        baseline=baseline,
        candidate=candidate,
        paired_case_ids=baseline.reviewed_case_ids,
        metric_deltas=deltas,
    )
